### PR TITLE
New Parameters: outlinedBorder and outlinedBorder

### PR DESCRIPTION
**Pull request by Alecsplus**
I added 2 simple parameters to the showMonthPicker method.

1 - outlinedBorder
There is a new parameter that change the shape of the border of the selected month, Default is CircleBorder()

2 - headerTitle
There is a new parameter that add a simple widget on the top of the dialog

### CODE REVIEW

**Comment by Macacoazul01** [comment]
Can you send samples of some uses for the headerTitle?

**Comment by Alecsplus** [comment]
Surely.... 
I my code I wrote something like this:

`showMonthPicker(
                          context: context,
                          headerTitle: Container(
                            padding: const EdgeInsets.only(bottom: 16),
                            child: Text(AppLocalizations.of(context).selectExpiringDate,
                                style: Theme.of(context).textTheme.labelLarge),
                          ));`

And this is the result:

calendar

**Comment by Macacoazul01** [comment]
This will be a nice update to the package, tks for the PR!

Gonna try to merge and launch an update later tonight

**Comment by Macacoazul01** [comment]
@Alecsplus published in 2.12

**Pull request merged**
